<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.6; }
        .invoice-box { max-width: 800px; margin: auto; padding: 30px; }
        .header { display: table; width: 100%; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .logo { font-size: 28px; font-weight: bold; color: #2563eb; display: table-cell; }
        .invoice-info { text-align: right; display: table-cell; font-size: 14px; }
        .details { margin-top: 40px; width: 100%; display: table; }
        .bill-to { display: table-cell; }
        .items-table { width: 100%; border-collapse: collapse; margin-top: 40px; }
        .items-table th { background: #f8fafc; border-bottom: 1px solid #e2e8f0; padding: 12px; text-align: left; }
        .items-table td { padding: 12px; border-bottom: 1px solid #e2e8f0; }
        .total-section { margin-top: 30px; text-align: right; }
        .total-amount { font-size: 20px; font-weight: bold; color: #2563eb; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #94a3b8; }
    </style>
</head>
<body>
    <div class="invoice-box">
        <div class="header">
            <div class="logo">INVOICE PRO</div>
            <div class="invoice-info">
                Date: {{ date('d-m-Y') }}<br>
                Invoice #: INV-{{ rand(1000, 9999) }}
            </div>
        </div>

        <div class="details">
            <div class="bill-to">
                <strong>BILL TO:</strong><br>
                {{ $client_name }}<br>
                {{ $client_email }}
            </div>
        </div>

        <table class="items-table">
            <thead>
                <tr>
                    <th>Description</th>
                    <th style="text-align: center;">Qty</th>
                    <th style="text-align: right;">Price</th>
                    <th style="text-align: right;">Subtotal</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $item }}</td>
                    <td style="text-align: center;">{{ $qty }}</td>
                    <td style="text-align: right;">${{ number_format($price, 2) }}</td>
                    <td style="text-align: right;">${{ number_format($total, 2) }}</td>
                </tr>
            </tbody>
        </table>

        <div class="total-section">
            <p>Grand Total</p>
            <div class="total-amount">${{ number_format($total, 2) }}</div>
        </div>

        <div class="footer">
            Thank you for your business!<br>
            Generated by Your Personal Invoice SaaS
        </div>
    </div>
</body>
</html>